/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNewChatRouteImport } from './routes/_authenticated/new-chat'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedInviteRouteImport } from './routes/_authenticated/invite'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedChallengesRouteImport } from './routes/_authenticated/challenges'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedStoriesNewRouteImport } from './routes/_authenticated/stories.new'
import { Route as AuthenticatedStoriesIdRouteImport } from './routes/_authenticated/stories.$id'
import { Route as AuthenticatedRevealIdRouteImport } from './routes/_authenticated/reveal.$id'
import { Route as AuthenticatedPostIdRouteImport } from './routes/_authenticated/post.$id'
import { Route as AuthenticatedPUsernameRouteImport } from './routes/_authenticated/p.$username'
import { Route as AuthenticatedJoinTokenRouteImport } from './routes/_authenticated/join.$token'
import { Route as AuthenticatedChatIdRouteImport } from './routes/_authenticated/chat.$id'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminBroadcastRouteImport } from './routes/_authenticated/admin.broadcast'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewChatRoute = AuthenticatedNewChatRouteImport.update({
  id: '/new-chat',
  path: '/new-chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInviteRoute = AuthenticatedInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChallengesRoute = AuthenticatedChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoriesNewRoute = AuthenticatedStoriesNewRouteImport.update({
  id: '/stories/new',
  path: '/stories/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoriesIdRoute = AuthenticatedStoriesIdRouteImport.update({
  id: '/stories/$id',
  path: '/stories/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevealIdRoute = AuthenticatedRevealIdRouteImport.update({
  id: '/reveal/$id',
  path: '/reveal/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostIdRoute = AuthenticatedPostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPUsernameRoute = AuthenticatedPUsernameRouteImport.update({
  id: '/p/$username',
  path: '/p/$username',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJoinTokenRoute = AuthenticatedJoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatIdRoute = AuthenticatedChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBroadcastRoute =
  AuthenticatedAdminBroadcastRouteImport.update({
    id: '/broadcast',
    path: '/broadcast',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/challenges': typeof AuthenticatedChallengesRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/invite': typeof AuthenticatedInviteRoute
  '/me': typeof AuthenticatedMeRoute
  '/new-chat': typeof AuthenticatedNewChatRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/chat/$id': typeof AuthenticatedChatIdRoute
  '/join/$token': typeof AuthenticatedJoinTokenRoute
  '/p/$username': typeof AuthenticatedPUsernameRoute
  '/post/$id': typeof AuthenticatedPostIdRoute
  '/reveal/$id': typeof AuthenticatedRevealIdRoute
  '/stories/$id': typeof AuthenticatedStoriesIdRoute
  '/stories/new': typeof AuthenticatedStoriesNewRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/challenges': typeof AuthenticatedChallengesRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/invite': typeof AuthenticatedInviteRoute
  '/me': typeof AuthenticatedMeRoute
  '/new-chat': typeof AuthenticatedNewChatRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/chat/$id': typeof AuthenticatedChatIdRoute
  '/join/$token': typeof AuthenticatedJoinTokenRoute
  '/p/$username': typeof AuthenticatedPUsernameRoute
  '/post/$id': typeof AuthenticatedPostIdRoute
  '/reveal/$id': typeof AuthenticatedRevealIdRoute
  '/stories/$id': typeof AuthenticatedStoriesIdRoute
  '/stories/new': typeof AuthenticatedStoriesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/challenges': typeof AuthenticatedChallengesRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/invite': typeof AuthenticatedInviteRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/new-chat': typeof AuthenticatedNewChatRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/chat/$id': typeof AuthenticatedChatIdRoute
  '/_authenticated/join/$token': typeof AuthenticatedJoinTokenRoute
  '/_authenticated/p/$username': typeof AuthenticatedPUsernameRoute
  '/_authenticated/post/$id': typeof AuthenticatedPostIdRoute
  '/_authenticated/reveal/$id': typeof AuthenticatedRevealIdRoute
  '/_authenticated/stories/$id': typeof AuthenticatedStoriesIdRoute
  '/_authenticated/stories/new': typeof AuthenticatedStoriesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/challenges'
    | '/inbox'
    | '/invite'
    | '/me'
    | '/new-chat'
    | '/onboarding'
    | '/search'
    | '/settings'
    | '/upload'
    | '/admin/broadcast'
    | '/admin/support'
    | '/chat/$id'
    | '/join/$token'
    | '/p/$username'
    | '/post/$id'
    | '/reveal/$id'
    | '/stories/$id'
    | '/stories/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/forgot-password'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/challenges'
    | '/inbox'
    | '/invite'
    | '/me'
    | '/new-chat'
    | '/onboarding'
    | '/search'
    | '/settings'
    | '/upload'
    | '/'
    | '/admin/broadcast'
    | '/admin/support'
    | '/chat/$id'
    | '/join/$token'
    | '/p/$username'
    | '/post/$id'
    | '/reveal/$id'
    | '/stories/$id'
    | '/stories/new'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/challenges'
    | '/_authenticated/inbox'
    | '/_authenticated/invite'
    | '/_authenticated/me'
    | '/_authenticated/new-chat'
    | '/_authenticated/onboarding'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/upload'
    | '/_authenticated/'
    | '/_authenticated/admin/broadcast'
    | '/_authenticated/admin/support'
    | '/_authenticated/chat/$id'
    | '/_authenticated/join/$token'
    | '/_authenticated/p/$username'
    | '/_authenticated/post/$id'
    | '/_authenticated/reveal/$id'
    | '/_authenticated/stories/$id'
    | '/_authenticated/stories/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-chat': {
      id: '/_authenticated/new-chat'
      path: '/new-chat'
      fullPath: '/new-chat'
      preLoaderRoute: typeof AuthenticatedNewChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invite': {
      id: '/_authenticated/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AuthenticatedInviteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/challenges': {
      id: '/_authenticated/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AuthenticatedChallengesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stories/new': {
      id: '/_authenticated/stories/new'
      path: '/stories/new'
      fullPath: '/stories/new'
      preLoaderRoute: typeof AuthenticatedStoriesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stories/$id': {
      id: '/_authenticated/stories/$id'
      path: '/stories/$id'
      fullPath: '/stories/$id'
      preLoaderRoute: typeof AuthenticatedStoriesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reveal/$id': {
      id: '/_authenticated/reveal/$id'
      path: '/reveal/$id'
      fullPath: '/reveal/$id'
      preLoaderRoute: typeof AuthenticatedRevealIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post/$id': {
      id: '/_authenticated/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof AuthenticatedPostIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/p/$username': {
      id: '/_authenticated/p/$username'
      path: '/p/$username'
      fullPath: '/p/$username'
      preLoaderRoute: typeof AuthenticatedPUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/join/$token': {
      id: '/_authenticated/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof AuthenticatedJoinTokenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$id': {
      id: '/_authenticated/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof AuthenticatedChatIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/broadcast': {
      id: '/_authenticated/admin/broadcast'
      path: '/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AuthenticatedAdminBroadcastRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBroadcastRoute: typeof AuthenticatedAdminBroadcastRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBroadcastRoute: AuthenticatedAdminBroadcastRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedChallengesRoute: typeof AuthenticatedChallengesRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedInviteRoute: typeof AuthenticatedInviteRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedNewChatRoute: typeof AuthenticatedNewChatRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedChatIdRoute: typeof AuthenticatedChatIdRoute
  AuthenticatedJoinTokenRoute: typeof AuthenticatedJoinTokenRoute
  AuthenticatedPUsernameRoute: typeof AuthenticatedPUsernameRoute
  AuthenticatedPostIdRoute: typeof AuthenticatedPostIdRoute
  AuthenticatedRevealIdRoute: typeof AuthenticatedRevealIdRoute
  AuthenticatedStoriesIdRoute: typeof AuthenticatedStoriesIdRoute
  AuthenticatedStoriesNewRoute: typeof AuthenticatedStoriesNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedChallengesRoute: AuthenticatedChallengesRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedInviteRoute: AuthenticatedInviteRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedNewChatRoute: AuthenticatedNewChatRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedChatIdRoute: AuthenticatedChatIdRoute,
  AuthenticatedJoinTokenRoute: AuthenticatedJoinTokenRoute,
  AuthenticatedPUsernameRoute: AuthenticatedPUsernameRoute,
  AuthenticatedPostIdRoute: AuthenticatedPostIdRoute,
  AuthenticatedRevealIdRoute: AuthenticatedRevealIdRoute,
  AuthenticatedStoriesIdRoute: AuthenticatedStoriesIdRoute,
  AuthenticatedStoriesNewRoute: AuthenticatedStoriesNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
